INSERT INTO subject (name) VALUES ('Arts & Photography');
INSERT INTO subject (name) VALUES ('Biographies & Memoirs');
INSERT INTO subject (name) VALUES ('Business & Money');
INSERT INTO subject (name) VALUES ('Calendars');
INSERT INTO subject (name) VALUES ('Children''s Books');
INSERT INTO subject (name) VALUES ('Christian Books & Bibles');
INSERT INTO subject (name) VALUES ('Comics & Graphic Novels');
INSERT INTO subject (name) VALUES ('Computers & Technology');
INSERT INTO subject (name) VALUES ('Cookbooks, Food & Wine');
INSERT INTO subject (name) VALUES ('Crafts, Hobbies & Home');
INSERT INTO subject (name) VALUES ('Education & Teaching');
INSERT INTO subject (name) VALUES ('Engineering & Transportation');
INSERT INTO subject (name) VALUES ('Health, Fitness & Dieting');
INSERT INTO subject (name) VALUES ('History');
INSERT INTO subject (name) VALUES ('Humor & Entertainment');
INSERT INTO subject (name) VALUES ('Law');
INSERT INTO subject (name) VALUES ('LGBTQ+ Books');
INSERT INTO subject (name) VALUES ('Literature & Fiction');
INSERT INTO subject (name) VALUES ('Medical Books');
INSERT INTO subject (name) VALUES ('Mystery, Thriller & Suspense');
INSERT INTO subject (name) VALUES ('Parenting & Relationships');
INSERT INTO subject (name) VALUES ('Politics & Social Sciences');
INSERT INTO subject (name) VALUES ('Reference');
INSERT INTO subject (name) VALUES ('Religion & Spirituality');
INSERT INTO subject (name) VALUES ('Romance');
INSERT INTO subject (name) VALUES ('Science & Math');
INSERT INTO subject (name) VALUES ('Science Fiction & Fantasy');
INSERT INTO subject (name) VALUES ('Self-Help');
INSERT INTO subject (name) VALUES ('Sports & Outdoors');
INSERT INTO subject (name) VALUES ('Teen & Young Adult');
INSERT INTO subject (name) VALUES ('Test Preparation');
INSERT INTO subject (name) VALUES ('Travel');